# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-13 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.IntegerField(db_index=True, default='1', primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(default=False, max_length=200, unique='True')),
                ('hostel', models.CharField(default=False, max_length=20)),
                ('discp', models.TextField(blank=True)),
                ('company', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('year', models.CharField(default='2018', max_length=20)),
                ('degree', models.CharField(default='BTech', max_length=100)),
                ('city', models.CharField(default='Mumbai', max_length=100)),
                ('department', models.CharField(default='Civil', max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('alloted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-tags', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='mentor',
            name='tags',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to='registration.Tag'),
        ),
    ]
